### PR TITLE
Added Bengali translation for README and updated base files

### LINKED ISSUE #1: Transaltions needed!
If you speak another language which isn't english, please help translating `README.md` and `CONTRIBUTING.md`.

- Fork this repository
- Create a new folder called `languages`
- Create your file called the file you're translating and the language like this `README_es.md` for Spanish
- Open a pull request

Every contributing is welcome ❤️

### PR DESCRIPTION
**Pull request by arpankumarde**
# Added Bengali translation for README and updated base files

This pull request adds Bengali translation for the README.md file and updates the base README.md and CONTRIBUTION.md files to include a link to the translated version.

Partly fixes #1 

## Why ?
This pull request aims to make the project more accessible and inclusive for Bengali speakers who want to learn about it or contribute to it.

## Changes

The tasks involved in this pull request are:

- [x] Created a new file named README-bengali.md with the Bengali translation of the README file
- [x] Updated the base README file to include a link to the Bengali translation
- [x] Fixed the links and typos of the base README file
- [x] Updated the language of CONTRIBUTION file to make it more user friendly

The expected outcome of this issue is to have a fully functional Bengali translation of the README file and updated base files that reflect the changes.

## Testing

The translated README.md file was previewed on GitHub and verified that the formatting and links are working correctly. The base README.md and CONTRIBUTION.md files were also previewed on GitHub and checked for any typos or broken links.

### CODE REVIEW

**Review by iSaulX — APPROVED** [review]

**Comment by iSaulX** [comment]
Thanks!! Merging now ❤️

**Comment by arpankumarde** [comment]
Thanks for merging! ❤️ 
Could you please add `hacktober` and `hacktoberfest-accepted` labels to this PR? It would help me climb up the ladder!

**Comment by iSaulX** [comment]
> Thanks for merging! ❤️ Could you please add `hacktoberfest` and `hacktoberfest-accepted` labels to this PR? It would help me climb up the ladder!

Sure!

**Comment by arpankumarde** [comment]
Thanks a lot ❤

**Pull request merged**
